type Query {
  me: User,
  UserList: [User]
}

type Mutation {
  loginUser(username: String!, password: String!): String
}

type Subscription {
  TodoCreated: Todo,
  CommentCreated: Comment,
  TodoUpdated: Boolean
}

type User {
  id: Int,
  display_name: String,
  url: String,
  gender: String
}